# Generated by Django 4.2.11 on 2024-04-30 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Frontend', '0004_alter_quiz_correctanswer_alter_quiz_option1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='CorrectAnswer',
            field=models.TextField(default='None', max_length=500),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='Option1',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='Option2',
            field=models.TextField(max_length=50),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='Option3',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='Option4',
            field=models.TextField(default=None, max_length=500),
        ),
    ]
